spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  application:
    name: mall
  rabbitmq:
    username: guest
    password: guest
    host: 192.168.1.20
    port: 5672
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  data:
    mongodb:
      uri: mongodb://192.168.1.21:27017/mall
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.1.21:9300
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 10000
mybatis:
  type-aliases-package: com.mall.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
feign:
  hystrix:
    enabled: true
